# Generated by Django 6.1.1 on 2026-10-01 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware_store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='critical_stock',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
