# Generated by Django 6.1.1 on 2026-10-01 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware_store', '0002_product_critical_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
